[[constraint]]
  name = "github.com/moleculer-go/moleculer"
  version = "0.2.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/novalagung/gubrak"
  version = "1.0.0"

[[constraint]]
  name = "go.mongodb.org/mongo-driver"
  version = "1.1.1"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.10"

[[constraint]]
  name = "github.com/lib/pq"
  version = "1.2.0"
