[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "gopkg.in/fsnotify/fsnotify.v1"

[[constraint]]
  name = "github.com/moleculer-go/moleculer"
  version = "0.2.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/novalagung/gubrak"
  version = "1.0.0"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.10"

[[constraint]]
  branch = "master"
  name = "github.com/tevjef/go-runtime-metrics"

[[constraint]]
  name = "gopkg.in/rethinkdb/rethinkdb-go.v5"
  version = "5.0.1"
