version: "3.2"

services:

  traefik:
    image: "traefik:v1.7.14-alpine"
    command: --api --ping --metrics --docker --docker.domain=docker.localhost --logLevel=INFO
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/etc/traefik:/etc/traefik:ro
    extra_hosts:
      - my.host:$IP_LOCALHOST
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.docker.localhost"
      - "traefik.docker.network=traefik"
      - "traefik.port=8080"
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443

networks:
  traefik:
    external:
      name: traefik
