version: "3.2"

services:

  kibana:
    build: ./kibana/
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=kibana"
      - "traefik.frontend.rule=Host:kibana.docker.localhost"
      - "traefik.port=5601"
      - "traefik.docker.network=traefik"
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    networks:
      - traefik

networks:
  traefik:
    external:
      name: traefik
